"""Mirror the company_facts registry into docs/company/company-facts.md.

The existing CompanyContextService scans docs/company/*.md and feeds the result
to MCP retrieval tools (company_docs_index, company_search_docs). Writing the
registry there is the cheapest way to make facts part of the "company
definition" that flows everywhere Zero looks.

The file path follows CompanyContextService._resolve_docs_root() so the mirror
lands where the docs index will see it. The mirror is idempotent: re-rendering
identical content is a no-op.
"""

from __future__ import annotations

from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Optional

from app.services.company_context_service import get_company_context_service
from app.services.company_facts_service import get_company_facts_service


_FACTS_FILE_NAME = "company-facts.md"
_HEADER = (
    "---\n"
    "owner: company\n"
    "status: generated\n"
    "source_of_truth: company_facts database table\n"
    "generator: company_facts_markdown_mirror\n"
    "---\n"
    "\n"
    "<!-- generated by app/services/company_facts_markdown_mirror.py - do not hand-edit -->\n"
    "\n"
    "# ADA AI LLC - Company Facts Registry\n"
    "\n"
    "This file mirrors the structured `company_facts` table. Each row is an\n"
    "artifact captured at task completion (or recorded manually) and represents\n"
    "the canonical company definition surface for Zero, MCP tools, and reports.\n"
    "\n"
    "**Sensitive values are written verbatim - this file is gitignored.**\n"
    "\n"
)


def _domain_label(domain: Optional[str]) -> str:
    return domain if domain else "Uncategorized"


class CompanyFactsMarkdownMirror:
    def __init__(self) -> None:
        self._last_content: Optional[str] = None

    def _docs_root(self) -> Path:
        return get_company_context_service().docs_root

    async def refresh(self) -> Optional[Path]:
        facts = await get_company_facts_service().list_facts()
        content = self._render(facts)
        if content == self._last_content:
            return None
        path = self._docs_root() / _FACTS_FILE_NAME
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        except OSError:
            return None
        self._last_content = content
        return path

    def _render(self, facts) -> str:
        if not facts:
            return _HEADER + "_No company facts captured yet._\n"

        grouped: dict[str, list] = defaultdict(list)
        for fact in facts:
            grouped[_domain_label(fact.domain)].append(fact)

        lines: list[str] = [_HEADER]
        for domain in sorted(grouped.keys()):
            lines.append(f"## {domain}\n\n")
            for fact in grouped[domain]:
                value_display = fact.value
                lines.append(f"### {fact.label}\n\n")
                lines.append(f"- **Key**: `{fact.key}`\n")
                lines.append(f"- **Value**: `{value_display}`\n")
                if fact.sensitive:
                    lines.append("- **Sensitive**: yes\n")
                if fact.evidence_url:
                    lines.append(f"- **Evidence**: {fact.evidence_url}\n")
                if fact.source_task_id:
                    lines.append(f"- **Source task**: `{fact.source_task_id}`\n")
                if fact.source and fact.source != "task_completion":
                    lines.append(f"- **Origin**: {fact.source}\n")
                if fact.notes:
                    lines.append(f"- **Notes**: {fact.notes}\n")
                if fact.updated_at or fact.created_at:
                    ts = (fact.updated_at or fact.created_at).isoformat()
                    lines.append(f"- **Recorded**: {ts}\n")
                lines.append("\n")
        return "".join(lines)


@lru_cache()
def get_company_facts_mirror() -> CompanyFactsMarkdownMirror:
    return CompanyFactsMarkdownMirror()
