"""Add faceprints table — Feature-52 vision speaker ID.

Persistent face fingerprint per identity. Mirrors the voiceprints table
exactly so the meeting pipeline can match captured face crops to a known
person, the same way it already matches diarized voice clusters via
voiceprints.

Embedding is a 128-dim float vector via pgvector. The MVP uses
imagehash-derived bit vectors padded into 128 dims (limited cross-meeting
accuracy); a follow-up swaps in a real face_recognition / insightface
embedding without schema changes.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "051"
down_revision = "050"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(
        """
        CREATE TABLE faceprints (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            display_name VARCHAR(200) NOT NULL UNIQUE,
            embedding vector(128) NOT NULL,
            sample_count INTEGER NOT NULL DEFAULT 0,
            is_primary BOOLEAN NOT NULL DEFAULT FALSE,
            source_meeting_id VARCHAR(64),
            face_crop_path TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.create_index("ix_faceprints_display_name", "faceprints", ["display_name"])


def downgrade() -> None:
    op.drop_index("ix_faceprints_display_name", table_name="faceprints")
    op.drop_table("faceprints")
